services:
  - type: web
    name: mapraqti-forum
    env: node
    plan: starter
    repo: https://github.com/MaPraqti/NodeBB.git
    branch: master
    healthCheckPath: /
    nodeVersion: '20'

    envVars:
      - key: url
        value: "https://mapraqti-forum.onrender.com"
      - fromService:
          type: redis
          name: mapraqti-redis
          property: connectionString
        key: REDIS_URI

    buildCommand: npm install --production && ./nodebb build
    startCommand: "./nodebb start"

  - type: redis
    name: mapraqti-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru
