services:
  # שירות הווב עבור NodeBB
  - type: web
    name: mapraqti-forum
    env: node
    plan: starter
    repo: https://github.com/MaPraqti/NodeBB.git # !!! ודא שזה שם המשתמש הנכון שלך
    branch: master # !!! שיניתי מ-main ל-master כדי שיתאים למה שמופיע אצלך בתמונה
    healthCheckPath: /
    envVars:
      - key: url
        value: "https://mapraqti-forum.onrender.com" # נעדכן לדומיין הסופי בהמשך
      # --- זה החלק שהשתנה ---
      # במקום לבקש כל פרט בנפרד, אנו מבקשים את כל מחרוזת החיבור
      - fromService:
          type: redis
          name: mapraqti-redis
          property: connectionString # שינוי: מבקשים connectionString במקום host/port/password
        key: REDIS_URI # שינוי: שם המשתנה החדש

    # פקודת ה-Build שונתה כדי להשתמש במשתנה החדש
    buildCommand: |
      npm install --production
      # שינוי: שימוש ב-redis:uri במקום בפרטים הנפרדים
      ./nodebb setup --no-prompt --database=redis --redis:uri=$REDIS_URI
      ./nodebb build
    startCommand: "./nodebb start"

  # שירות בסיס הנתונים Redis - ללא שינוי
  - type: redis
    name: mapraqti-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru
