 services:
  # שירות הווב עבור NodeBB
  - type: web
    name: mapraqti-forum
    env: node
    plan: starter
    repo: https://github.com/MaPraqti/NodeBB.git # ודא שזה שם המשתמש הנכון
    branch: master
    healthCheckPath: /
    envVars:
      - key: url
        value: "https://mapraqti-forum.onrender.com"
      - fromService:
          type: redis
          name: mapraqti-redis
          property: connectionString
        key: REDIS_URI

    # --- זה החלק שהשתנה והתחזק ---
    # איחדנו את כל הפקודות לשורה אחת עם && ביניהן
    buildCommand: npm install --production && ./nodebb setup --no-prompt --database=redis --redis:uri=$REDIS_URI && ./nodebb build
    startCommand: "./nodebb start"

  # שירות בסיס הנתונים Redis - ללא שינוי
  - type: redis
    name: mapraqti-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru
