services:
  # זהו שירות הווב שיריץ את הפורום
  - type: web
    name: mapraqti-forum # שם השירות ב-Render
    env: node
    plan: starter # מומלץ להתחיל עם תוכנית בסיסית בתשלום. אפשר לשנות ל-free לניסיון.
    repo: https://github.com/MaPraqti/NodeBB.git # !!! החלף בשם המשתמש שלך
    branch: main # הערה: NodeBB משתמש ב-master, אך Render יכול לעבוד עם main. נשאיר main כרגע.
    healthCheckPath: /
    envVars:
      # בהמשך נעדכן את זה לדומיין האמיתי שלנו
      - key: url 
        value: "https://mapraqti-forum.onrender.com"
      # שלושת המשתנים הבאים יקבלו את הערכים שלהם אוטומטית משירות ה-Redis למטה
      - fromService:
          type: redis
          name: mapraqti-redis
          property: host
        key: REDIS_HOST
      - fromService:
          type: redis
          name: mapraqti-redis
          property: port
        key: REDIS_PORT
      - fromService:
          type: redis
          name: mapraqti-redis
          property: password
        key: REDIS_PASSWORD
    # פקודת ההתקנה: היא משתמשת במשתנים שלמעלה כדי להגדיר את החיבור לבסיס הנתונים
    buildCommand: |
      npm install --production
      ./nodebb setup --no-prompt --database=redis --redis:host=$REDIS_HOST --redis:port=$REDIS_PORT --redis:password=$REDIS_PASSWORD
      ./nodebb build
    startCommand: "./nodebb start"

  # זהו שירות בסיס הנתונים
  - type: redis
    name: mapraqti-redis
    plan: free
    ipAllowList: [] 
    maxmemoryPolicy: allkeys-lru
