services:
  - type: web
    name: mapraqti-forum
    env: node
    plan: starter
    
    # --- התיקון המרכזי כאן ---
    # 1. אנחנו פונים ישירות למאגר הרשמי של NodeBB
    repo: https://github.com/NodeBB/NodeBB.git
    
    # 2. אנחנו בוחרים את הגרסה היציבה שאנחנו רוצים מתוך התגיות שלהם
    branch: v3.9.4 # !!! ודא שזו הגרסה היציבה העדכנית ביותר
    # --- סוף התיקון ---

    healthCheckPath: /
    envVars:
      - key: url
        value: "https://mapraqti-forum.onrender.com" # נעדכן לדומיין סופי בהמשך
      - fromService:
          type: redis
          name: mapraqti-redis
          property: connectionString
        key: REDIS_URL

    buildCommand: |
      npm install --production
      export REDIS_HOST=$(echo $REDIS_URL | sed -e 's/redis.*@//' -e 's/:.*//')
      export REDIS_PORT=$(echo $REDIS_URL | sed -e 's/.*://')
      export REDIS_PASSWORD=$(echo $REDIS_URL | sed -e 's/redis.*:\/\///' -e 's/@.*//')
      ./nodebb setup --no-prompt --database=redis --redis:host=$REDIS_HOST --redis:port=$REDIS_PORT --redis:password=$REDIS_PASSWORD
      ./nodebb build
    
    startCommand: "./nodebb start"

  - type: redis
    name: mapraqti-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru
