services:
  - type: web
    name: mapraqti-forum
    env: node
    plan: starter # מומלץ ליציבות. ניתן לשנות ל-free לניסיון.
    repo: https://github.com/MaPraqti/NodeBB.git # !!! החלף בשם המשתמש שלך
    branch: main
    healthCheckPath: /
    envVars:
      # בשלב 4 נעדכן את זה לדומיין הסופי האמיתי
      - key: url 
        value: "https://mapraqti-forum.onrender.com" 
      - fromService:
          type: redis
          name: mapraqti-redis
          property: host
        key: REDIS_HOST
      - fromService:
          type: redis
          name: mapraqti-redis
          property: port
        key: REDIS_PORT
      - fromService:
          type: redis
          name: mapraqti-redis
          property: password
        key: REDIS_PASSWORD
    
    # --- START OF CRITICAL FIX ---
    # ה-Build Command המתוקן:
    # 1. נכנסים לתיקיית install
    # 2. מריצים npm install כדי להתקין את התלויות
    # 3. חוזרים תיקייה אחת למעלה (לשורש הפרויקט)
    # 4. מריצים את סקריפט ההתקנה וה-build משם
    buildCommand: |
      cd install
      npm install --production
      cd ..
      ./nodebb setup --no-prompt --database=redis --redis:host=$REDIS_HOST --redis:port=$REDIS_PORT --redis:password=$REDIS_PASSWORD
      ./nodebb build
    # --- END OF CRITICAL FIX ---

    startCommand: "./nodebb start"

  - type: redis
    name: mapraqti-redis
    plan: free
    ipAllowList: [] 
    maxmemoryPolicy: allkeys-lru
